---
- name: Configure Bastion Reverse Proxy
  hosts: bastion
  become: true

  tasks:

    - name: Install nginx
      apt:
        name: nginx
        update_cache: yes
        state: present

    - name: Configure reverse proxy
      copy:
        dest: /etc/nginx/sites-available/app
        content: |
          server {
              listen 80;

              location / {
                  proxy_pass http://10.0.10.144;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
              }
          }

    - name: Enable site
      file:
        src: /etc/nginx/sites-available/app
        dest: /etc/nginx/sites-enabled/app
        state: link

    - name: Restart nginx
      service:
        name: nginx
        state: restarted