name: Secure Deploy

on:
  workflow_dispatch:
    inputs:
      tf_action:
        description: "Terraform action"
        required: true
        type: choice
        options:
          - plan
          - apply
          - destroy
        default: plan

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-2

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 🔐 Security Scans
      - name: Secrets Scan
        uses: gitleaks/gitleaks-action@v2

      - name: Dependency Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs

      # AWS Setup
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: generate variable.tfvars
        working-directory: terraform
        run: |
          cat <<EOF > terraform.tfvars
          key_name = "${{ secrets.TF_VAR_key_name }}"
          db_password = "${{ secrets.TF_VAR_db_password }}"
          domain_name = "${{ secrets.TF_VAR_domain_name }}"

          EOF

      # Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init -reconfigure

      - name: Terraform validate
        working-directory: terraform
        run: terraform validate
      
      - name: Terraform plan
        if: github.event.inputs.tf_action == 'plan'
        working-directory: terraform
        run: terraform plan

      - name: Terraform Apply
        if: github.event.inputs.tf_action == 'apply'
        working-directory: terraform
        run: terraform apply -auto-approve

      - name: Terraform Destroy
        if: github.event.inputs.tf_action == 'destroy'
        working-directory: terraform
        run: terraform destroy -auto-approve

      # Capture Terraform outputs
      - name: Capture Terraform Outputs
        if: github.event.inputs.tf_action == 'apply'
        working-directory: terraform
        run: |
          echo "APP_IP=$(terraform output -raw app_node_ip)" >> $GITHUB_ENV
          echo "BASTION_IP=$(terraform output -raw bastion_node_ip)" >> $GITHUB_ENV
          echo "DB_IP=$(terraform output -raw db_node_ip)" >> $GITHUB_ENV

      # Show Outputs (optional)
      - name: Show Outputs
        if: github.event.inputs.tf_action == 'apply'
        run: |
          echo "App Node IP: ${{ env.APP_IP }}"
          echo "Bastion Node IP: ${{ env.BASTION_IP }}"
          echo "DB IP: ${{ env.DB_IP }}"
          echo "Domain Name: ${{ secrets.TF_VAR_domain_name }}"

      # Setup SSH Key
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/ec2.pem
          chmod 400 ~/.ssh/ec2.pem

      # Create Ansible Inventory
      - name: Create Ansible Inventory
        run: |
          cat <<EOF > terraform/inventory.ini
          [app]
          ${{ env.APP_IP }} ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/ec2.pem

          [bastion]
          ${{ env.BASTION_IP }} ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/ec2.pem

          [db]
          ${{ env.DB_IP }} ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/ec2.pem
          EOF

      # # Replace APP IP in nginx config ( ansible/templates/nginx.conf.j2)
      # - name: Update nginx.conf.j2 with APP IP
      #   run: |
      #     sed -i "s/{{ app_ip }}/\${{ env.APP_IP }}/g" ansible/templates/nginx.conf.j2

      # Test SSH Connections
      - name: Test SSH Connections
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/ec2.pem ec2-user@${{ env.BASTION_IP }} "echo 'SSH connection to Bastion successful!'"

      # Install Ansible
      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Ensure python3-apt exists
        run:  sudo apt-get update && sudo apt-get install -y python3-apt

      # Wait for servers to be ready
      - name: Wait for servers
        run: sleep 60

      # # Setup Python for Ansible
      # - name: Setup Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.11'

      # # Run Ansible OS Hardening
      # - name: Run Ansible OS Hardening
      #   run: ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i terraform/inventory.ini ansible/ansible-playbook.yml

      # Deploy Application

      - name: Install Ansible
        run: |
          python3 -m pip install --upgrade pip
          pip install ansible

      - name: Run Ansible Deploy
        run: ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i terraform/inventory.ini ansible/ansible-playbook.yml